

#########################################################
#							#
#			tmux.conf			#
#							#
#########################################################


##
# Reload
##

unbind r
bind r source-file ~/.tmux.conf \;display-message "Config reloaded"

##
# Prefix
##

set -g prefix C-s

##
# Basic
##

set -g mouse on
set-option -g status-position top
set -g base-index 1
set -g renumber-windows on
set-option -g default-terminal "tmux-256color"
set-option -g allow-rename on
set-option -g automatic-rename off
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

##
# Pane Navigation
##

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

##
# Catppuccin Config
##

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

##
# Status Line Config
##

set -g status-left-length 100
set -g status-right-length 100
set -g status-interval 1
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -g @cpu_percentage_format "%3.0f%%"

##
# Window styling
##

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_window_text "#W"

##
# Plugins List
##

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v3'

run '~/.tmux/plugins/tpm/tpm'
